;BOTÓN CONECTADO EN RA0 CON RESISTOR PULL UP(CLICK)
;LED PARA CONTROLAR EL ENCENDIDO Y APAGADO DEL LED EN RD5
    
    LIST P=18F4550		;LISTAMOS PIC A UTILIZAR
    #INCLUDE<P18F4550.INC>	;AGREGAMOS LAS LIBRERIAS DEL PIC
    #DEFINE BOTON	PORTA,RA1
    #DEFINE LED1   PORTD,6
    #DEFINE LED2   PORTD,5
    #DEFINE LED3   PORTD,4
    #DEFINE LED4   PORTD,3
    #DEFINE LED5   PORTD,2
    #DEFINE LED6   PORTD,1
    #DEFINE LED7   PORTD,0
    #DEFINE LED8   PORTD,7
    ORG	.0
  
 SETTING    BSF	 TRISA,1
	    CLRF PORTA
	    CLRF LATA
	    CLRF TRISD
	    CLRF PORTD
	    CLRF LATD
	    MOVLW .15
	    MOVWF ADCON1
	    MOVLW .7
	    MOVWF CMCON
	    MOVLW B'11010111'
	    MOVWF T0CON
	    
		
MAIN	BTFSC	BOTON
	BRA     MAIN
OTRA	CALL    DELAYB
	BTFSS   BOTON
	BRA     OTRA
	GOTO    SERIE1
	
SERIE1  CLRF    PORTD
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	BTFSC	BOTON
	BRA     E1
OTRA1	CALL    DELAYB
	BTFSS   BOTON
	BRA     OTRA1
	GOTO    OFFL
	
E1	BTG     LED1
	BTG     LED7
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	BTFSC	BOTON
	BRA     E2
OTRA2	CALL    DELAYB
	BTFSS   BOTON
	BRA     OTRA2
	GOTO    OFFL
	
E2	BTG     LED2
	BTG     LED6
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	BTFSC	BOTON
	BRA     E3
OTRA3	CALL    DELAYB
	BTFSS   BOTON
	BRA     OTRA3
	GOTO    OFFL
	
E3	BTG     LED3
	BTG     LED5
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	BTFSC	BOTON
	BRA     E4
OTRA4	CALL    DELAYB
	BTFSS   BOTON
	BRA     OTRA4
	GOTO    OFFL
	
E4	BTG     LED4
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	BTFSC	BOTON
	BRA     E5
OTRA5	CALL    DELAYB
	BTFSS   BOTON
	BRA     OTRA5
	GOTO    OFFL
	
E5	BTG     LED4
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	BTFSC	BOTON
	BRA     E6
OTRA6	CALL    DELAYB
	BTFSS   BOTON
	BRA     OTRA6
	GOTO    OFFL
	
E6	BTG     LED3
	BTG     LED5
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	BTFSC	BOTON
	BRA     E7
OTRA7	CALL    DELAYB
	BTFSS   BOTON
	BRA     OTRA7
	GOTO    OFFL
	
E7	BTG     LED2
	BTG     LED6
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	BTFSC	BOTON
	BRA     E8
OTRA8	CALL    DELAYB
	BTFSS   BOTON
	BRA     OTRA8
	GOTO    OFFL
	
E8	BTG     LED1
	BTG     LED7
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	BTFSC	BOTON
	BRA     SERIE1
OTRA9	CALL    DELAYB
	BTFSS   BOTON
	BRA     OTRA9
	GOTO    OFFL
	
SERIE2  BTG     LED1
	BTG     LED2
	BTG     LED3
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	BTFSC	BOTON
	BRA     D1
OTRA11	CALL    DELAYB
	BTFSS   BOTON
	BRA     OTRA11
	GOTO    OFFL
	
D1	BTG     LED1
	BTG     LED2
	BTG     LED3
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	BTFSC	BOTON
	BRA     D2
OTRA22	CALL    DELAYB
	BTFSS   BOTON
	BRA     OTRA22
	GOTO    OFFL
	
D2	BTG     LED5
	BTG     LED6
	BTG     LED7
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	BTFSC	BOTON
	BRA     D3
OTRA33	CALL    DELAYB
	BTFSS   BOTON
	BRA     OTRA33
	GOTO    OFFL
	
D3	BTG     LED5
	BTG     LED6
	BTG     LED7
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	BTFSC	BOTON
	BRA     D4
OTRA44	CALL    DELAYB
	BTFSS   BOTON
	BRA     OTRA44
	GOTO    OFFL
	
D4	BTG     LED4
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	BTFSC	BOTON
	BRA     D5
OTRA55	CALL    DELAYB
	BTFSS   BOTON
	BRA     OTRA55
	GOTO    OFFL
	
D5	BTG     LED4
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	BTFSC	BOTON
	BRA     D6
OTRA66	CALL    DELAYB
	BTFSS   BOTON
	BRA     OTRA66
	GOTO    OFFL
	
D6	BTG     LED1
	BTG     LED2
	BTG     LED3
	BTG     LED4
	BTG     LED5
	BTG     LED6
	BTG     LED7
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	BTFSC	BOTON
	BRA     D7
OTRA77	CALL    DELAYB
	BTFSS   BOTON
	BRA     OTRA77
	GOTO    OFFL
	
D7	BTG     LED1
	BTG     LED2
	BTG     LED3
	BTG     LED4
	BTG     LED5
	BTG     LED6
	BTG     LED7
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	BTFSC	BOTON
	BRA     D8
OTRA88	CALL    DELAYB
	BTFSS   BOTON
	BRA     OTRA88
	GOTO    OFFL
	
D8	BTG     LED1
	BTG     LED2
	BTG     LED3
	BTG     LED4
	BTG     LED5
	BTG     LED6
	BTG     LED7
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	BTFSC	BOTON
	BRA     D9
OTRA99	CALL    DELAYB
	BTFSS   BOTON
	BRA     OTRA99
	GOTO    OFFL
	
D9	BTG     LED1
	BTG     LED2
	BTG     LED3
	BTG     LED4
	BTG     LED5
	BTG     LED6
	BTG     LED7
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	CALL    DELAYL
	BTFSC	BOTON
	BRA     SERIE2
OTRA111	CALL    DELAYB
	BTFSS   BOTON
	BRA     OTRA111
	GOTO    OFFL
	
	
OFFL    BCF     PORTD,RD0
	BCF     PORTD,RD1
	BCF     PORTD,RD2
	BCF     PORTD,RD3
	BCF     PORTD,RD4
	BCF     PORTD,RD5
	BCF     PORTD,RD6
	BRA     MAIN
		
DELAYB  CLRF    TMR0L
	MOVLW   .251
	MOVWF   TMR0L
ASK1	BTFSS   INTCON,TMR0IF
	BRA     ASK1
	BCF     INTCON,TMR0IF
	RETURN
	
DELAYL  CLRF    TMR0L
	MOVLW   .100
	MOVWF   TMR0L
ASK2	BTFSS   INTCON,TMR0IF
	BRA     ASK2
	BCF     INTCON,TMR0IF
	RETURN
	END