;BOTÓN CONECTADO EN RA0 CON RESISTOR PULL UP(CLICK)
    
    LIST P=18F4550		;LISTAMOS PIC A UTILIZAR
    #INCLUDE<P18F4550.INC>	;AGREGAMOS LAS LIBRERIAS DEL PIC
			; GFEDCBA
    #DEFINE CERO	B'00111111'
    #DEFINE UNO  	B'00110000'
    #DEFINE DOS 	B'01011011'
    #DEFINE TRES	B'01001111'
    #DEFINE CUATRO      B'01100110'
    #DEFINE CINCO	B'01101101'
    #DEFINE BOTON	PORTA,RA1
    #DEFINE BOTON1	PORTA,RA2 
    #DEFINE CONTADOR    .30
    ORG	.0
  
 SETTING    BSF	 TRISA,1
	    CLRF PORTA
	    CLRF LATA
	    BSF  TRISA,2
	    CLRF TRISD
	    CLRF PORTD
	    CLRF LATD
	    MOVLW .15
	    MOVWF ADCON1
	    MOVLW .7
	    MOVWF CMCON
	    MOVLW B'11010111'
	    MOVWF T0CON
		
MAIN	MOVLW   CERO
	MOVWF   PORTD
	MOVLW   H'00'
	MOVWF   CONTADOR
	GOTO    ONOFF
	
ONOFF   BTFSC	BOTON
	BRA     ONOFF2
OTRA	CALL    DELAY
	BTFSS   BOTON
	BRA     OTRA
	GOTO    INCR
	
ONOFF2	BTFSC   BOTON1
	BRA     ONOFF
OTRA2	CALL    DELAY
	BTFSS   BOTON1
	BRA     OTRA2
	GOTO    DECR
	
INCR    MOVLW   .5
	CPFSEQ  CONTADOR
	INCF    CONTADOR,F
	CALL    TABLA
	MOVWF   PORTD
	GOTO    ONOFF2
	
DECR    MOVLW   .0
	CPFSEQ  CONTADOR
	DECF    CONTADOR,F
        CALL    TABLA
        MOVWF   PORTD
	GOTO    ONOFF
	
TABLA   MOVFF   CONTADOR,WREG
	MULLW   .2
	MOVFF   PRODL,WREG
	ADDWF	PCL,F		;W=PA PCL=28+W
	RETLW	CERO		;PCL=30 W=3F
	RETLW	UNO
	RETLW	DOS
	RETLW	TRES
	RETLW	CUATRO
	RETLW	CINCO
	
	
DELAY   CLRF    TMR0L
	MOVLW   .249
	MOVWF   TMR0L
ASK	BTFSS   INTCON,TMR0IF
	BRA     ASK
	BCF     INTCON,TMR0IF
	RETURN
	END


