;DOS INTERRUPCIONES DE ALTA PRIORIDAD + UNA DE BAJA PRIORIDAD
;programa de un contador de 0-3 ascendente
;int externa INT0 (pull down) prende un led (RB7) por 1 seg
;int externa INT1 (PULL UP) prende y apagada (2 VECES) un led en RB6
;int externa INT2 (pull down) muestra una caria en display (PORTD) por 2 seg
    LIST P=18F4550
    #INCLUDE<P18F4550.INC>
    
    CBLOCK	H'00' 
    WREGC
    BSRC
    STATUSC
    TMR0LC
    WREGCB
    STATUSCB
    BSRCB
    TMR0LCB
    ENDC
    
    ORG	.0
    GOTO    SETTING
    
    ORG	.8
    GOTO    BACKUP
    
    ORG	.24
    
BACKUP_BAJA
	MOVFF	WREG,WREGCB
	MOVFF	STATUS,STATUSCB
	MOVFF	BSR,BSRCB
	MOVFF	TMR0L,TMR0LCB

ASK3	BTFSS	INTCON3,INT2IF
	GOTO	SALIR_INT_BAJA
	BCF	INTCON3,INT2IF
	MOVLW	B'00101001'
	MOVWF	PORTD
	CALL	DELAY
	CALL	DELAY
	MOVLW	B'00000000'
	MOVWF	PORTB
	
SALIR_INT_BAJA
	MOVFF	WREGCB,WREG
	MOVFF	STATUSCB,STATUS
	MOVFF	BSRCB,BSR
	MOVFF	TMR0LCB,TMR0L
	RETFIE

BACKUP	MOVFF	WREG,WREGC
	MOVFF	STATUS,STATUSC
	MOVFF	BSR,BSRC
	MOVFF	TMR0L,TMR0LC

ASK1	BTFSS	INTCON,INT0IF
	GOTO	ASK2
	BCF	INTCON,INT0IF
	BSF	PORTB,7
	CALL	DELAY
	CALL	DELAY
	BCF	PORTB,7
	GOTO	SALIR_INT
	
ASK2	BTFSS	INTCON3,INT1IF
	GOTO	SALIR_INT
	BCF	INTCON3,INT1IF
	BSF	PORTB,6
	CALL	DELAY
	CALL	DELAY
	BCF	PORTB,6
	CALL	DELAY
	CALL	DELAY
	BSF	PORTB,6
	CALL	DELAY
	CALL	DELAY
	BCF	PORTB,6

SALIR_INT 
	MOVFF	WREGC,WREG
	MOVFF	STATUSC,STATUS
	MOVFF	BSRC,BSR
	MOVFF	TMR0LC,TMR0L
	RETFIE
	
SETTING	CLRF	TRISD
	CLRF	PORTD
	CLRF	LATD
	MOVLW	B'00000111'
	MOVWF	TRISB
	CLRF	PORTB
	CLRF	LATB
	MOVLW	B'11010111'
	MOVWF	T0CON
	BSF	RCON,IPEN
	MOVLW	B'11010000'
	MOVWF	INTCON
	MOVLW	B'11010101'
	MOVWF	INTCON2
	MOVLW	B'01011000'
	MOVWF	INTCON3
	MOVLW	.15
	MOVWF	ADCON1
	
MAIN	MOVLW	B'00111111'
	MOVWF	PORTD
	CALL	DELAY
	CALL	DELAY
	MOVLW	B'00001010'
	MOVWF	PORTD
	CALL	DELAY
	CALL	DELAY
	MOVLW	B'01011101'
	MOVWF	PORTD
	CALL	DELAY
	CALL	DELAY
	MOVLW	B'01011011'
	MOVWF	PORTD
	CALL	DELAY
	CALL	DELAY
	GOTO	MAIN
	
DELAY	CLRF	TMR0L
	MOVLW	.50
	MOVWF	TMR0L
	CLRF	WREG
ASK	CPFSEQ  TMR0L
	BRA	ASK
	RETURN
	END


