;Catodo de 2 bits que muestre las opciones en numeros de las entradas
    LIST P=18F4550
    #INCLUDE <P18F4550.INC>
    
    #DEFINE	CERO	0X3F
    #DEFINE	UNO	0X06
    #DEFINE	DOS	0X5B
    #DEFINE	TRES	0X4F
    
    ORG	.0  ;Escribe la primera instrucción en el espacio 0
    
SETTING	    
	CLRF	PORTA  ;LIMPIAR PORTA
	CLRF	LATA   ;LIMPIAR LATA
	SETF	TRISA  ;HACER TODAS ENTRADAS DE TRISA
	MOVLW	B'00001111'
	MOVWF	ADCON1  ;DECIR QUE SON ENTRADAS
	MOVLW	B'0000111'
	MOVWF	CMCON  ;APAGAR EL COMPARADOR DE VOLTAJE
	CLRF	PORTD  ;DECIR QUE SON SALIDAS
	CLRF	TRISD  ;DECIR QUE SON SALIDAS
	
DECO	
	MOVLW	B'00000011'
	ANDWF	PORTA,W
	MULLW	.2
	MOVF	PRODL,W
	CALL	TABLA
	MOVWF	PORTD
	GOTO	DECO
TABLA	ADDWF	PCL,F
	RETLW	CERO
	RETLW	UNO
	RETLW	DOS
	RETLW	TRES
	
END
	
	


