;PROGRAMA QUE MUESTRA LA SE?AL BINARIA DE 10 BITS,
;CORRESPONDIENTE AL VOLTAJE ANALOGICO QUE INGRESA POR AN0,
;ENCIENDE UN LED EN RA1 CUANDO EL VOLTAJE ES MAYOR A 3.5 VOLTS
    
    LIST P=18F4550		;LISTAMOS PIC A UTILIZAR
    #INCLUDE<P18F4550.INC>	;AGREGAMOS LAS LIBRERIAS DEL PIC
    
    ORG .0
    
SETTING	BSF	TRISA,0
	BCF	TRISA,1
	CLRF	PORTA
	CLRF	LATA
	CLRF	TRISB
	CLRF	PORTB
	CLRF	LATB
	CLRF	TRISD
	CLRF	PORTD
	CLRF	LATD
	MOVLW	B'00000001'
	MOVWF	ADCON0
	MOVLW	B'00001110'
	MOVWF	ADCON1
	MOVLW	B'10010111'
	MOVWF	ADCON2
	MOVLW	.7
	MOVWF	CMCON
	
MAIN	BSF	ADCON0,GO_DONE
ASK	BTFSC	ADCON0,GO_DONE
	GOTO	ASK
	MOVFF	ADRESL,PORTB
	MOVFF	ADRESH,PORTD
	BTFSS	ADRESH,1
	GOTO	APAGA	
	BTFSS	ADRESH,0
	GOTO	CHECK
	GOTO	PRENDE

CHECK	MOVLW	B'11001011'
	CPFSGT	ADRESL
	GOTO	APAGA
	GOTO	PRENDE

PRENDE	BSF	PORTA,1
	GOTO	MAIN
	
APAGA	BCF	PORTA,1
	GOTO	MAIN
	END