;giro derecha de motor a pasos
    
    LIST    P=18F4550
    #INCLUDE<P18F4550.INC>
    
    #DEFINE BOTON	PORTA,RA1
    CBLOCK  .0
    ENDC
	ORG	.0
	
SETTING	CLRF	PORTD
	CLRF	TRISD
	MOVLW	B'11000111'
	MOVWF	T0CON
	BSF	 TRISA,1
	CLRF	PORTA
	CLRF	LATA
	MOVLW	.15
	MOVWF	ADCON1
	MOVLW	.7
	MOVWF	CMCON
Boton
	BTFSC	BOTON
	BRA     Boton
OTRA	CALL    DELAYB
	BTFSS   BOTON
	BRA     OTRA
	GOTO    Izquierda
	

Izquierda
	CALL DELAYB
	MOVLW	B'00001001'
	MOVWF	PORTD
	CALL	DELAY
	MOVLW	B'00000011'
	MOVWF	PORTD
	CALL	DELAY
	MOVLW	B'00000110'
	MOVWF	PORTD
	CALL	DELAY
	MOVLW	B'00001100'
	MOVWF	PORTD
	CALL	DELAY
	CALL    DELAYB
	BTFSS   BOTON
	BRA     Izquierda
	GOTO    Derecha
	
Derecha	CALL DELAYB
	MOVLW	B'00001100'
	MOVWF	PORTD
	CALL	DELAY
	MOVLW	B'00000110'
	MOVWF	PORTD
	CALL	DELAY
	MOVLW	B'00000011'
	MOVWF	PORTD
	CALL	DELAY
	MOVLW	B'00001001'
	MOVWF	PORTD
	CALL	DELAY
	CALL    DELAYB
	BTFSS   BOTON
	BRA     Derecha
	GOTO    Izquierda
	
DELAYB  CLRF    TMR0L
	MOVLW   .249
	MOVWF   TMR0L
ASK1	BTFSS   INTCON,TMR0IF
	BRA     ASK1
	BCF     INTCON,TMR0IF
	RETURN	
	
DELAY	CLRF	TMR0L
	MOVLW	.220
	MOVWF	TMR0L
ASK	BTFSS	INTCON,TMR0IF
	BRA	ASK
	BCF	INTCON,TMR0IF
	RETURN
	END