;PAR E IMPAR  con 2 switch manejar el control de las salidas de PORTB
;ISMAEL FLORES MELÉNDEZ
	;Default
    LIST P=18F4550
    #INCLUDE<P18F4550.INC>
    
    ;CONFIG1L    DIR 300000h 	20h
    ;CONFIG	 PLLDIV=1	 ; 
    ;CONFIG	 CPUDIV=OSC1_PLL2        ;CUANDO SE USA XTAL	 
    CONFIG	 FOSC=INTOSCIO_EC        ;OSCILADOR INTERNO, RA6 COMO PIN, USB USA OSC EC
    CONFIG	 FCMEN=OFF                     ;DESHABILITDO EL MONITOREO DEL RELOJ
    CONFIG	 IESO=OFF
    ;CONFIG2L    DIR 300002H	38h
    CONFIG	 PWRT=ON                           ;PWRT HABILITADO
    CONFIG       BOR=OFF		 ;BROWN OUT RESET DESHABILITADO
    CONFIG       BORV=3		 ;RESET AL MINIMO VOLTAJE NO UTILZADO EN ESTE CASO
    CONFIG	 VREGEN=ON	 ;REGULADOR DE USB ENCENDIDO
    ;CONFIG2H    DIR 300003H	1Eh
    CONFIG	 WDT=OFF                          ;PERRO GUARDIAN (WATCH DOG) DESHABILITADO
    CONFIG       WDTPS=32768                 ;TIMER DEL WATCHDOG 
    ;CONFIG3H	 DIR 300005H	85h
    CONFIG	 CCP2MX=ON	 ;CCP2 MULTIPLEXADAS CON RC1	
    CONFIG	 PBADEN=OFF                      ;PUERTO B PINES DEL 0 AL 4 ENTRADAS DIGITALES
    CONFIG       LPT1OSC=OFF	 ;TIMER1 CONFIGURADO PARA OPERAR EN BAJA POTENCIA
    CONFIG	 MCLRE=ON                         ;MASTER CLEAR HABILITADO
    ;CONFIG4L    DIR 300006H	81h
    CONFIG	 STVREN=ON	                      ;SI EL STACK SE LLENA CAUSE RESET		
    CONFIG	 LVP=OFF		 ;PROGRAMACI?N EN BAJO VOLTAJE APAGADO
    CONFIG	 ICPRT=OFF	                       ;REGISTRO ICPORT DESHABILITADO
    CONFIG       XINST=OFF                        ;SET DE EXTENCION DE INSTRUCCIONES Y DIRECCIONAMIENTO INDEXADO OFF
    ;CONFIG5L    DIR 300008H	0Fh
    CONFIG	 CP0=OFF		 ;LOS BLOQUES DEL C?DIGO DE PROGRAMA
    CONFIG	 CP1=OFF                             ;NO ESTAN PROTEGIDOS
    CONFIG	 CP2=OFF		 
    CONFIG	 CP3=OFF
    ;CONFIG5H    DR 300009H		0Ch
    CONFIG	 CPB=OFF		 ;SECTOR BOOT NO ESTA PROTEGIDO
    CONFIG	 CPD=OFF		 ;EEPROM NO PROTEGIDA
    ;CONFIG6L    DIR 30000AH	0Fh
    CONFIG	 WRT0=OFF	                      ;BLOQUES NO PROTEGIDOS CONTRA ESCRITURA
    CONFIG	 WRT1=OFF
    CONFIG	 WRT2=OFF
    CONFIG	 WRT3=OFF
    ;CONFIG6H	 DIR 30000BH	E0h
    CONFIG	 WRTC=OFF		 ;CONFIGURACION DE REGISTROS NO PROTEGIDO
    CONFIG	 WRTB=OFF		 ;BLOQUE BOOTEABLE NO PROTEGIDO
    CONFIG	 WRTD=OFF		 ;EEPROMDE DATOS NO PROTEGIDA

    ;CONFIG7L    DIR 30000CH	0Fh
    CONFIG	 EBTR0=OFF	 	;TABLAS DE LETURA NO PROTEGIDAS
    CONFIG	 EBTR1=OFF
    CONFIG	 EBTR2=OFF
    CONFIG	 EBTR3=OFF
    ;CONFIG7H    DIR 30000DH	40h
    CONFIG	 EBTRB=OFF	   
    
    
	;Declaraciones Previas
    ENTRADA    EQU	    .10
    ORG	    .0
    
SETTINGS
	;CONFIGURACIONES DEL PUERTO A
    ;LIMPIAR PUERTO
    SETF    TRISA	
    CLRF    PORTA
    CLRF    LATA    
    MOVLW   .15		
    MOVWF   ADCON1	;DEFINIR QUE TODAS SON ENTRADAS
    MOVLW   .7
    MOVWF   CMCON	;Apagar el comparador de voltaje
    
	;CONFIGURACIONES DEL PUERTO B
    ;LIMPIAR PUERTO
    CLRF    PORTB
    CLRF    LATB
    CLRF    TRISB
    CLRF    WREG
    
MAIN	
    MOVFF   PORTA,ENTRADA  ;MOVER LOS DATOS DE PORTA A ENTRADA
    MOVLW   B'0000011'  
    ANDWF   ENTRADA,F	;VALIDAR SOLO LOS PRIMEROS 3 BITS PARA NUM1
    BTFSS   ENTRADA,0
    GOTO    CASE1
    GOTO    CASE2
    
;EL BIT MENOS SIGNIFICATIVO ES 0
CASE1
    BTFSS   ENTRADA,1
    GOTO CASE11  ;EL SEGUNDO BIT ES 0
    GOTO CASE12  ;EL SEGUNDO BIT ES 1
    
CASE11    ;NADA
    MOVLW   B'00000000'
    MOVWF   PORTB
    GOTO MAIN    ;REGRESAR A MAIN
    
CASE12  ;IMPAR
    MOVLW   B'01010101'
    MOVWF   PORTB
    GOTO MAIN    ;REGRESAR A MAIN

;EL BIT MENOS SIGNIFICATIVO ES 1    
CASE2  
    BTFSS   ENTRADA,1
    GOTO CASE21  ;EL SEGUNDO BIT ES 0
    GOTO CASE22	 ;EL SEGUNDO BIT ES 1
    
CASE21   ;PAR
    MOVLW   B'10101010'
    MOVWF   PORTB
    GOTO MAIN
    
    
CASE22   ;TODOS
    MOVLW   B'11111111'
    MOVWF   PORTB
    GOTO MAIN
    
    END




