;PORTB = PA + 8
    
    LIST P=18F4550
    #INCLUDE<P18F4550.INC>
	  
    ;PALABRA DE CONFIGURACION
    CTE	    EQU	    .8
	    
	    ORG	.0

CONFIGU	    CLRF    TRISB
	    CLRF    PORTB
	    CLRF    LATB
	    MOVLW   .15
	    MOVWF   ADCON1  ;TODAS LAS ENTRADAS DEL PIC SEAN DIG
	    
	    MOVLW   .7
	    MOVWF   CMCON   ;COMPARADOR DE VOLTAJES CONTECTADO EN PA ESTA APAGADO
	    
	    MOVLW   B'00000011'
	    MOVWF   TRISA
	    CLRF    PORTA
	    CLRF    LATA
	    
SUMA	MOVLW	.8
	ADDWF	PORTA,W
	MOVWF	PORTB
	GOTO	SUMA
	END   
    


