;ESTE PROGRAMA GIRA UN BOTON A 180 CON CUN BOTON
    LIST P=18F4550
    #INCLUDE <P18F4550.INC>
    
    #DEFINE BOTON	PORTA,0
    CBLOCK  .0
    ENDC
    
    ORG	    .0
SETTING	    BSF		TRISA,0
	    CLRF	PORTA
	    CLRF	LATA
	    CLRF	PORTD
	    CLRF	TRISD
	    CLRF	LATD
	    MOVLW	.15
	    MOVWF	ADCON1
	    MOVLW	.7
	    MOVWF	CMCON
	    MOVLW	B'11000111'
	    MOVWF	T0CON
	    GOTO	PREGUNTA
	    
MAIN	    BTFSC	BOTON
	    BRA		MAIN
OTRA	    CALL	DELAY1
	    BTFSS	BOTON
	    BRA		OTRA
	    RETURN
	
PREGUNTA    CALL	MAIN
	    GOTO	REPETIR
GIRAR	    MOVLW	B'00001100'
	    MOVWF	PORTD
	    CALL	DELAY
	    MOVLW	B'00000110'
	    MOVWF	PORTD
	    CALL	DELAY
	    MOVLW	B'00000011'
	    MOVWF	PORTD
	    CALL	DELAY
	    MOVLW	B'00001001'
	    MOVWF	PORTD
	    CALL	DELAY
	    RETURN
	    
REPETIR	    CALL	GIRAR
	    CALL	GIRAR
	    CALL	GIRAR
	    CALL	GIRAR
	    GOTO	PREGUNTA
	    
DELAY	    CLRF	TMR0L
	    MOVWF	.220
	    MOVWF	TMR0L
ASK	    BTFSS	INTCON, TMR0IF
	    BRA		ASK
	    BCF		INTCON, TMR0IF
	    RETURN
	 
DELAY1	    CLRF	TMR0L
	    MOVWF	.247
	    MOVWF	TMR0L
ASK1	    BTFSS	INTCON, TMR0IF
	    BRA		ASK
	    BCF		INTCON, TMR0IF
	    RETURN
	    END
