;este código realiza PA<2>=1 SI Y SOLO SI  PA<4>=0
;			LED		    SW
    LIST P=18F4550
    #INCLUDE<P18F4550.INC>
    
#DEFINE LED PORTA,2    ;EQ SOLO IGUALA VALORES CON ETIQUETA    DEFINE IGUALA CADENA CON REGISTROS Y PUEDE ASIGNAR VALORES
	
	ORG	    .0    ;ESCRIBIR LA PRIMERA INSTRUCCIÓN EN 0
    
SETTING	    CLRF    PORTA
	    CLRF    LATA    ;NO ES TAN NECESARIO
	    CLRF    TRISA   ;DEFINIR QUE TODAS SON SALIDAS
	    BCF	    TRISA,2  ;PONER 0 LA POSICIÓN 2 DE PORTA
	    BSF	    TRISA,4  ;PONER 1 EN POSICION 4 DE PORTA
	    MOVLW   B'00001111'  ;15
	    MOVWF   ADCON1  ;TODAS LAS ENTRADAS SEAN DIGITALES
	    MOVLW   B'00000111'  ;NUMERO 7 BINARIO
	    MOVWF   CMCON   ;APAGAR EL COMPARADOR DE VOLTAJE EN EL PORTA

ONL1	BTFSC	PORTA,4   ;SI EL REGISTRO EN ESA POSICIÓN ES 0 SALTA
	GOTO	NO	;Ir a No sino salto
	GOTO	SI	;Ir a Si si salto
NO
	BCF	LED	;Apagar el led
	GOTO	ONL1	;Regresar a ONL1
	
SI	
	BSF	LED	;Encender el LED
	GOTO	ONL1	;Ir a Onl1
	
	END