;este código realiza PA<2>=1 SI Y SOLO SI  PA<4>=0
;			LED		    SW
    LIST P=18F4550
    #INCLUDE<P18F4550.INC>
    
    ;CONFIG1L   DIR 300000h 	20h
		;CONFIG	PLLDIV=1	 ; 
		;CONFIG	CPUDIV=OSC1_PLL2        ;CUANDO SE USA XTAL	 
			CONFIG	FOSC=INTOSCIO_EC        ;OSCILADOR INTERNO, RA6 COMO PIN, USB USA OSC EC
			CONFIG	FCMEN=OFF                     ;DESHABILITDO EL MONITOREO DEL RELOJ
			CONFIG	IESO=OFF
			;CONFIG2L  DIR 300002H	38h
				CONFIG	PWRT=ON                           ;PWRT HABILITADO
			CONFIG        BOR=OFF		 ;BROWN OUT RESET DESHABILITADO
			CONFIG        BORV=3		 ;RESET AL MINIMO VOLTAJE NO UTILZADO EN ESTE CASO
		CONFIG	VREGEN=ON	 ;REGULADOR DE USB ENCENDIDO
		;CONFIG2H  DIR 300003H	1Eh
		CONFIG	WDT=OFF                          ;PERRO GUARDIAN (WATCH DOG) DESHABILITADO
		CONFIG        WDTPS=32768                 ;TIMER DEL WATCHDOG 
		;CONFIG3H   DIR 300005H	85h
		CONFIG	CCP2MX=ON	 ;CCP2 MULTIPLEXADAS CON RC1	
		CONFIG	PBADEN=OFF                      ;PUERTO B PINES DEL 0 AL 4 ENTRADAS DIGITALES
		CONFIG        LPT1OSC=OFF	 ;TIMER1 CONFIGURADO PARA OPERAR EN BAJA POTENCIA
		CONFIG	MCLRE=ON                         ;MASTER CLEAR HABILITADO
		;CONFIG4L   DIR 300006H	81h
		CONFIG	STVREN=ON	                      ;SI EL STACK SE LLENA CAUSE RESET		
		CONFIG	LVP=OFF		 ;PROGRAMACIÒN EN BAJO VOLTAJE APAGADO
		CONFIG	ICPRT=OFF	                       ;REGISTRO ICPORT DESHABILITADO
	CONFIG        XINST=OFF                        ;SET DE EXTENCION DE INSTRUCCIONES Y DIRECCIONAMIENTO INDEXADO OFF
		;CONFIG5L   DIR 300008H	0Fh
		CONFIG	CP0=OFF		 ;LOS BLOQUES DEL CÒDIGO DE PROGRAMA
		CONFIG	CP1=OFF                             ;NO ESTAN PROTEGIDOS
		CONFIG	CP2=OFF		 
		CONFIG	CP3=OFF
		;CONFIG5H  DR 300009H		0Ch
		CONFIG	CPB=OFF		 ;SECTOR BOOT NO ESTA PROTEGIDO
		CONFIG	CPD=OFF		 ;EEPROM NO PROTEGIDA
		;CONFIG6L    DIR 30000AH	0Fh
		CONFIG	 WRT0=OFF	                      ;BLOQUES NO PROTEGIDOS CONTRA ESCRITURA
		CONFIG	 WRT1=OFF
		CONFIG	 WRT2=OFF
		CONFIG	 WRT3=OFF

		;CONFIG6H DIR 30000BH	E0h
		CONFIG	 WRTC=OFF		 ;CONFIGURACION DE REGISTROS NO PROTEGIDO
		CONFIG	 WRTB=OFF		 ;BLOQUE BOOTEABLE NO PROTEGIDO
		CONFIG	 WRTD=OFF		 ;EEPROMDE DATOS NO PROTEGIDA

		;CONFIG7L    DIR 30000CH	0Fh
		CONFIG	 EBTR0=OFF	 	;TABLAS DE LETURA NO PROTEGIDAS
		CONFIG	 EBTR1=OFF
		CONFIG	 EBTR2=OFF
		CONFIG	 EBTR3=OFF

		;CONFIG7H   DIR 30000DH	40h
		CONFIG	 EBTRB=OFF	                      ;TABLAS NO PROTEGIDAS
    
    
#DEFINE LED PORTA,2    ;EQ SOLO IGUALA VALORES CON ETIQUETA    DEFINE IGUALA CADENA CON REGISTROS Y PUEDE ASIGNAR VALORES
	
	ORG	    .0    ;ESCRIBIR LA PRIMERA INSTRUCCIÓN EN 0
    
SETTING	    CLRF    PORTA
	    CLRF    LATA    ;NO ES TAN NECESARIO
	    CLRF    TRISA   ;DEFINIR QUE TODAS SON SALIDAS
	    BCF	    TRISA,2  ;PONER 0 LA POSICIÓN 2 DE PORTA
	    BSF	    TRISA,4  ;PONER 1 EN POSICION 4 DE PORTA
	    MOVLW   B'00001111'  ;15
	    MOVWF   ADCON1  ;TODAS LAS ENTRADAS SEAN DIGITALES
	    MOVLW   B'00000111'  ;NUMERO 7 BINARIO
	    MOVWF   CMCON   ;APAGAR EL COMPARADOR DE VOLTAJE EN EL PORTA

ONL1	BTFSC	PORTA,4   ;SI EL REGISTRO EN ESA POSICIÓN ES 0 SALTA
	GOTO	NO	;Ir a No sino salto
	GOTO	SI	;Ir a Si si salto
NO
	BCF	LED	;Apagar el led
	GOTO	ONL1	;Regresar a ONL1
	
SI	
	BSF	LED	;Encender el LED
	GOTO	ONL1	;Ir a Onl1
	
	END